export default {
  login: "Alexey2001",
  id: 43443254,
  node_id: "MDQ6VXNlcjQzNDQzMjU0",
  avatar_url: "https://avatars1.githubusercontent.com/u/43443254?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Alexey2001",
  html_url: "https://github.com/Alexey2001",
  followers_url: "https://api.github.com/users/Alexey2001/followers",
  following_url: "https://api.github.com/users/Alexey2001/following{/other_user}",
  gists_url: "https://api.github.com/users/Alexey2001/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Alexey2001/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Alexey2001/subscriptions",
  organizations_url: "https://api.github.com/users/Alexey2001/orgs",
  repos_url: "https://api.github.com/users/Alexey2001/repos",
  events_url: "https://api.github.com/users/Alexey2001/events{/privacy}",
  received_events_url: "https://api.github.com/users/Alexey2001/received_events",
  type: "User",
  site_admin: false,
  name: "Alexey Andryushin",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 25,
  public_gists: 1,
  followers: 2,
  following: 7,
  created_at: "2018-09-20T13:05:59Z",
  updated_at: "2020-07-16T19:42:36Z"
  }
