export default [
  {
  login: "muyiniao",
  id: 45302242,
  node_id: "MDQ6VXNlcjQ1MzAyMjQy",
  avatar_url: "https://avatars0.githubusercontent.com/u/45302242?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/muyiniao",
  html_url: "https://github.com/muyiniao",
  followers_url: "https://api.github.com/users/muyiniao/followers",
  following_url: "https://api.github.com/users/muyiniao/following{/other_user}",
  gists_url: "https://api.github.com/users/muyiniao/gists{/gist_id}",
  starred_url: "https://api.github.com/users/muyiniao/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/muyiniao/subscriptions",
  organizations_url: "https://api.github.com/users/muyiniao/orgs",
  repos_url: "https://api.github.com/users/muyiniao/repos",
  events_url: "https://api.github.com/users/muyiniao/events{/privacy}",
  received_events_url: "https://api.github.com/users/muyiniao/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "npismenkov",
  id: 50764773,
  node_id: "MDQ6VXNlcjUwNzY0Nzcz",
  avatar_url: "https://avatars3.githubusercontent.com/u/50764773?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/npismenkov",
  html_url: "https://github.com/npismenkov",
  followers_url: "https://api.github.com/users/npismenkov/followers",
  following_url: "https://api.github.com/users/npismenkov/following{/other_user}",
  gists_url: "https://api.github.com/users/npismenkov/gists{/gist_id}",
  starred_url: "https://api.github.com/users/npismenkov/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/npismenkov/subscriptions",
  organizations_url: "https://api.github.com/users/npismenkov/orgs",
  repos_url: "https://api.github.com/users/npismenkov/repos",
  events_url: "https://api.github.com/users/npismenkov/events{/privacy}",
  received_events_url: "https://api.github.com/users/npismenkov/received_events",
  type: "User",
  site_admin: false
  }
  ]
